services:
  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./data:/mnt/data
      - $PWD/config.env:/etc/config.env
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    command: minio server --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      containers:
        ipv4_address: 192.168.226.104

networks:
  containers:
    external: true
